name: Deployment Workflow
on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Establish a Connection to Server and Update Website
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.SERVER_IP}}
                  username: ${{secrets.SERVER_USERNAME}}
                  key: ${{secrets.SSH_KEY}}
                  port: ${{secrets.SERVER_PORT}}
                  script_stop: true
                  script: |
                      cd /repos/notes-sample-works
                      git fetch
                      git checkout master
                      git reset --hard HEAD
                      git pull origin master
                      npm i
                      npm run build
                      pm2 stop notes-sample-works
                      pm2 start server/entry.express.js --name notes-sample-works
                      pm2 save
