name: Deploy
on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Deploy
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - run: |
                  npm i
                  npm run build
                  pwd
                  pm2 stop notes-sample-works || true
                  pm2 start server/entry.express.js --name notes-sample-works
                  pm2 save
