name: Deploy
on:
    push:
        branches: [master]

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-qwik.yml@master
        with:
            process-name: notes-sample-works
