name: Deploy
on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Deploy
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            - run: pm2 restart notes-sample-works
